### ISSUE TITLE
Timestamp decoding for videos from a A129 Duo is failing

### ISSUE THREAD

**Issue by donalhunt** [taneljairus/random-mapillary-stuff#7]
Model: Viofo A129 Duo
Firmware: v2.1 (Aug 2020)

I already tried adjusting the script to use moov containers but that hasn't helped.

```bash
$ python ts_processor.py --input 2021_0610_174405_029F.MP4 
Namespace(bearing_modifier=0.0, crop_bottom=0, crop_left=0, crop_right=0, crop_top=0, csv=0, device_override='', folder='output', input='/home/dhunt/Downloads/2021_0610_174405_029F.MP4', make=None, mask=None, metric_distance=0, min_coverage=90, min_points=5, min_speed=-1.0, model=None, sampling_interval=0.5, suppress_cv2_warnings=0, timeshift=0.0, timezone=0.0)
/home/xxxxxxx/Downloads/2021_0610_174405_029F.MP4
Novatek MP4 T
FPS : 30.0; LEN: 18000
Traceback (most recent call last):
  File "ts_processor.py", line 554, in <module>
    locdata,packetno = get_gps_data_nt(input_ts_file, device)
  File "ts_processor.py", line 329, in get_gps_data_nt
    currentdata["ts"] = datetime(year=2000+year, month=month, day=day, hour=hour, minute=minute, second=second).replace(tzinfo=timezone.utc).timestamp()
ValueError: month must be in 1..12
```

**Comment by donalhunt** [comment]
this is the input packet it is trying to process:

```
(b'eeGPS L\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x10\x00\x00\x00,\x00\x00\x00\x03\x00\x00\x00\x15\x00'
 b'\x00\x00\x06\x00\x00\x00\n\x00\x00\x00ANW\x00\xb68\xa1E%\x15OD=\nW>\x00\x00'
 b'KB\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
```

**Comment by GPSMapper** [comment]
Hi, please upload the sampe video to Google drive, I will have a look. Probably A129 uses a different storage pattern. 


________________________________
From: Donal Hunt ***@***.***>
Sent: Thursday, June 10, 2021 19:12
To: taneljairus/random-mapillary-stuff
Cc: Subscribed
Subject: [taneljairus/random-mapillary-stuff] Timestamp decoding for videos from a A129 Duo is failing (#7)
Model: Viofo A129 Duo
Firmware: v2.1 (Aug 2020)

I already tried adjusting the script to use moov containers but that hasn't helped.

```bash
$ python ts_processor.py --input 2021_0610_174405_029F.MP4 
Namespace(bearing_modifier=0.0, crop_bottom=0, crop_left=0, crop_right=0, crop_top=0, csv=0, device_override='', folder='output', input='/home/dhunt/Downloads/2021_0610_174405_029F.MP4', make=None, mask=None, metric_distance=0, min_coverage=90, min_points=5, min_speed=-1.0, model=None, sampling_interval=0.5, suppress_cv2_warnings=0, timeshift=0.0, timezone=0.0)
/home/xxxxxxx/Downloads/2021_0610_174405_029F.MP4
Novatek MP4 T
FPS : 30.0; LEN: 18000
Traceback (most recent call last):
  File "ts_processor.py", line 554, in <module>
    locdata,packetno = get_gps_data_nt(input_ts_file, device)
  File "ts_processor.py", line 329, in get_gps_data_nt
    currentdata["ts"] = datetime(year=2000+year, month=month, day=day, hour=hour, minute=minute, second=second).replace(tzinfo=timezone.utc).timestamp()
ValueError: month must be in 1..12
```

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/taneljairus/random-mapillary-stuff/issues/7

**Comment by donalhunt** [comment]
File is available at https://drive.google.com/file/d/1QKAe__3OjIIv1dLEXb1TGr26xSmfy1Sk/view (please request access since I don't want to leave it open to the world).

There is a chance that GPS data wasn't saved. I only updated the firmware today and turned the GPS back on just before recording these videos (a reboot may have been needed). Will record some more videos and verify if that's the case.

**Comment by GPSMapper** [comment]
OK, so the offset within the packet is slightly different.
Current script logic is not intelligent enough to detect offset properly, so script adjustment is required.
I will test some new data extraction logic which should be more universal.
Meanwhile, please replace lines 314 to 327 of the script with below code:

```
            hour = int.from_bytes(input_packet[42:46], byteorder='little')
            minute = int.from_bytes(input_packet[46:50], byteorder='little')
            second = int.from_bytes(input_packet[50:54], byteorder='little')
            year = int.from_bytes(input_packet[54:58], byteorder='little')
            month = int.from_bytes(input_packet[58:62], byteorder='little')
            day = int.from_bytes(input_packet[62:66], byteorder='little')
            active = chr(bs[66])
            lathem = chr(bs[67])
            lonhem = chr(bs[68])
            lat = fix_coordinates(lathem,struct.unpack('<f', input_packet[70:74]))
            lon = fix_coordinates(lonhem,struct.unpack('<f', input_packet[74:78]))
            speed_knots, = struct.unpack('<f', input_packet[78:82])
            speed = speed_knots * 1.6 / 3.6
            bearing, = struct.unpack('<f', input_packet[82:86])
```

or use the adjusted script found under this link:
https://drive.google.com/file/d/1-53OhYRt4nkaPwEL6RxHH0JqSQmZ-J49/view?usp=sharing

**Comment by donalhunt** [comment]
working like a charm! \o/
thank you...
